### ISSUE TITLE
Eu posso deixar um post em blank

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#1]
![image](https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/d9bf7c06-a34f-4331-8fb7-6bea904095de)

**Comment by matheus-kiyoshi** [comment]
bug fixed, thanks for the report! @Vytzz 

commit fix number 36 -> ec2d54b18ccbf70cd4cf7eb719d4472b1775acb4
