### ISSUE TITLE
Perfil

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#10]
A opacidade do header ocupa a imagem do banner, atrapalhando a visão do usuário que quer testar o estilo do perfil, não sei o que fazer para melhorar, mas isso atrapalha, boa sorte
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/61300744-79a7-402a-8f4f-095717e777b7">

**Comment by matheus-kiyoshi** [comment]
thanks for the request, @Vytzz !

commit number 38 enhance the header background -> d40fa94e12d3e2de3bca93821908c95263e1d02d
