### ISSUE TITLE
Criar conta

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#11]
Ao clicar em sign up
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/b183644d-6b50-4062-a162-e93802ddd435">
não acontece nada, aparece uma animação do mouseclick, mas não acontece nada

**Comment by matheus-kiyoshi** [comment]
This happens when filling in the information does not meet the requirements, soon an error warning appears to the user informing him. In this case the password is no longer than 8 characters.

Thanks for the report @Vytzz !

**Comment by matheus-kiyoshi** [comment]
Now if the account wasnt created, error modal will appear. If account was created, you will be pushed to login page.

commit number 39 --> 925279afee1db2f41a80d6156222edad7c7b85d1
