### ISSUE TITLE
Editar perfil

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#2]
Ao editar o perfil, só tem como salvar após mudar o nickname, mas ao mesmo tempo tem como deixar o nickname em blank
![image](https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/0aebd430-90e4-4e0c-a0f1-bd203340db98)
![image](https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/2fc4a2c7-d5a2-4d0c-b80c-c6331bf46812)

**Comment by matheus-kiyoshi** [comment]
thanks, @Vytzz !

commit number 37 fix that -> 82377370a866c34fcb59fde3f994cc7faddd0feb
