### ISSUE TITLE
Criar conta

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#3]
É possível criar usuários com espaços, tornando-os invisíveis
![image](https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/09ea22e7-8067-489d-ab4b-58069fe94ff6)

**Comment by matheus-kiyoshi** [comment]
thanks, bug fixed!

commit number 39 --> 925279afee1db2f41a80d6156222edad7c7b85d1

**Comment by matheus-kiyoshi** [comment]
thanks, bug fixed!

commit number 39 --> 925279afee1db2f41a80d6156222edad7c7b85d1
