### ISSUE TITLE
Cria Conta #2

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#4]
Também tem como criar contas com emojis, e o famoso caractere invisível (ㅤ)
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/9aae480a-adce-4f8f-9559-6063c5ae7b94">
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/71f57d09-5059-4a43-94b8-48a31790f008">

**Comment by Victor-Dalbon** [comment]
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/cbf7ce03-127f-4079-b4c8-831f59e1cfed">

**Comment by matheus-kiyoshi** [comment]
thanks, bug fixed!

commit number 39 --> 925279afee1db2f41a80d6156222edad7c7b85d1
