### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#5]
Ao clicar em editar o perfil, não tem como voltar sem fechar o site.
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/1317143a-b799-4743-bc95-ee1bdb3f064d">

**Comment by matheus-kiyoshi** [comment]
thanks for the request!

commit number 41 fix it -> 08c5f7b41e1562290c90c350ab34756ce243e619
