### ISSUE TITLE
Editar Perfil

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#6]
A UI do botão Edit Perfil, que eu acho inútil aí, fica esticada ao colocar uma imagem no banner, por exmeplo:
ANTES
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/edf7b872-8ca7-423e-9eeb-5526fc15f963">
DEPOIS
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/889fa24f-6267-4d2f-8900-ed310b75edc8">

**Comment by matheus-kiyoshi** [comment]
button removed, thanks for the report, @Vytzz !

commit number 41 -> 08c5f7b41e1562290c90c350ab34756ce243e619
