### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#7]
Os posts estão organizados do mais antigo para os mais novos, mas é melhor ser ao contrário, os novos primeiros e os antigos depois
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/670beb82-2da7-424b-9915-52dda06c70d6">

**Comment by matheus-kiyoshi** [comment]
the latest commit on social media api fix this. Thanks for the report.
