### ISSUE TITLE
Create Post

### ISSUE THREAD

**Issue by Victor-Dalbon** [matheus-kiyoshi/socialmedia#9]
Ao clicar em Post, para fazer algum post, é impossível voltar para a home sem criar o post, ou fechar a página, se foi um miss-click você terá que fechar a página não podendo voltar a home facilmente após se arrepender
<img width="960" alt="image" src="https://github.com/matheus-kiyoshi/socialmedia/assets/135763462/79190193-a55a-4ff3-b49e-3d198812a5e0">

**Comment by matheus-kiyoshi** [comment]
button added, thanks for the request!

commit number 40 -> d2c6070680f7fb4c82a55e6c2a2281e1dcdb0e36
